package golib

import (
	"unsafe"
)

type DispatchMessage interface {
	DispatchKey() interface{}
}

// Generated by ArrayDispatcher.Add() or MapDispatcher.Add()
type DispatchKeyMixin /* implement DispatchMessage */ struct {
	dispatcher unsafe.Pointer
	key        uintptr
}

func (o DispatchKeyMixin) DispatchKey() interface{} {
	return o
}
